# Contents

- [Introduction](#introduction)
- [Series](#series)
- [Data Frame](#dataframe)
- [File Reading](#file-reading)
  - [CSV](#csv)
  - [JSON](#json)
- [Inspecting Data](#inspecting-data)
- [Data Cleaning](#data-cleaning)
  - [Remove Rows](#remove-rows)
  - [Replace Empty Vaues](#replace-empty-values)
  - [Remove Duplicates](#remove-duplicates)
  - [Wrong Format](#wrong-format)
  - [Wrong Data](#wrong-data)
- [Column Operation](#column-operation)
  - [Insertion](#column-insertion)
  - [Updation](#column-updation)
  - [Deletion](#column-deletion)
- [Feature Scaling](#feature-scaling)
  - [Standardization](#standardization-z-score-normalization)
  - [Min-Max Scaling](#min-max-scaling-normalization)
  - [Robust Scaling](#robust-scaling)
  - [MaxAbs Scaling](#maxabs-scaling)
- [Filtering](#filtering)
- [Concatenating](#concatenating)
- [Merging](#merging)
  - [Inner Join](#inner-join)
  - [Outer Join](#outer-join)
  - [Left Join](#left-join)
  - [Right Join](#right-join)
  - [Transformation](#transformation)

# Introduction

Pandas is used for working with data sets, it is used to analyze data. It has functions for analyzing, cleaning, exploring, and manipulating data.

**What Can Pandas Do?**
Pandas gives you answers about the data. Like:

- Is there a correlation between two or more columns?
- What is average value?
- Max value?
- Min value?

Pandas are also able to delete rows that are not relevant, or contains wrong values, like empty or NULL values. This is called cleaning the data.

- `pandas.__version__` - return the version of pandas
- `pandas.DataFrame()` - a data structure constructed with rows and columns, similar to a database.
- `pandas.options.display.max_rows` - return or set the system maximum number of row

# Series

A Pandas Series is like a column in a table.

In [6]:
import pandas as pd
name=["Jack","John","Mark","Zuck"]
student_table = pd.Series(name)

In [7]:
student_table

0    Jack
1    John
2    Mark
3    Zuck
dtype: object

The above script generate name column in student table.

you can access each column value by their index.

you can also overried the index label with your custom label by `index` argument.

In [3]:
student_table = pd.Series(name,index = ["a", "b", "c","d"])

In [4]:
student_table

a    Jack
b    John
c    Mark
d    Zuck
dtype: object

now you can access it both by number index as well as you custom index.

In [13]:
# print(student_table['a'])
print(student_table.iloc[0]) # student_table[0] will be removed

Jack

if you use dictornary instead of list, the keys of the dictionary become the labels

In [14]:
name={"a":"Jack","b":"John","c":"Mark","d":"Zuck"}

if label is set `index` argument is used to get specific item, if not, it set label.

The length of data and the length of `index` argument should be same. The data used in **series** or **dataframe** can be anytype.

# DataFrame

A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

In [17]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}
df = pd.DataFrame(data)

`loc` attribute return one or more specified row

In [20]:
print(df.loc[0]) # return first row

calories    420
duration     50
Name: 0, dtype: int64

In [21]:
print(df.loc[[0,2]]) # return specified index - 0th, 2nd

   calories  duration
0       420        50
2       390        45

In [22]:
print(df.loc[0:2]) # return list of indexes from 0 to 2

   calories  duration
0       420        50
1       380        40
2       390        45

you can override the label in dataframe also

In [24]:
df = pd.DataFrame(data, index = ["a", "b", "c"])

In [25]:
df

   calories  duration
a       420        50
b       380        40
c       390        45

# File Reading

## CSV

`pandas.read_csv()` - read csv file and store in data frame

If you have a large DataFrame with many rows, Pandas will only return the first 5 rows, and the last 5 rows

In [ ]:
df = pd.read_csv('data.csv')

`dataframe.toString()` - return entire dataframe as **string representation**, it will output the entire DataFrame to the console.

In [26]:
df.to_string()

'   calories  duration\na       420        50\nb       380        40\nc       390        45'

`dataframe.to_csv(filename)` - use to generate csv file

## JSON

`pandas.read_json()` - read json file and store in data frame

JSON objects have the same format as Python dictionaries. If your JSON code is not in a file, but in a Python Dictionary, you can load it into a DataFrame directly:

# Inspecting Data

- `info()` - provide summary
- `head()` - return the first nth rows
- `tail()` - return the last nth rows
- `shape` - return a tuple represent the dimension
- `describe()` - generates descriptive statistics like max, min, mean, std etc for numerical columns by default.
- `columns` - returns an Index object containing the column labels
- `index` - return the index(row label) range
- `dtypes` - return data type of each column
- `isnull()` - return boolean value indicating whether each value is NaN
- `notnull()` - return boolean value indicating whether each value is not NaN
- `sum()`,`mean()`,`median()`,`std()`,`min()`,`max()` - apply on each column and return value according to their name
- `value.counts()` - return a series containing counts of unique values for a given column. Ex: `df['column_name'].value_counts()`, if you want to consider `NaN` as unique value put `dropna=False` argument.
- `sample()` - return random samples, you can specify the number of row with n attribute
- `corr()` - computes pairwise correlation of columns, excluding NA/null values.
- `nunique()` - returns the number of unique values for each column.
- `df['column_name'].str.string_method()` - perform string related operation like `len()`, `upper()`, `lower()`, `substr()`, `replace()` etc.t

all the method ignore `NaN` value while calculating, `skipna=False` argument is use to consider `NaN` value.

**Perform Aggregations:**

In [33]:
custom_agg=df.agg({
  "calories": ["sum", "mean"],
  "duration": ["min", "max"],
  # "c": "count"
})

In [34]:
custom_agg

         calories  duration
sum   1190.000000       NaN
mean   396.666667       NaN
min           NaN      40.0
max           NaN      50.0

# Data Cleaning

Data cleaning means fixing bad data in your data set. Bad data could be:

- Empty cells
- Data in wrong format
- Wrong data
- Duplicates

- `isna()` - detect missing values and return boolean datafram
- `isna().sum()` - detect and count the number of missing values for each column

## Remove Rows

`df.dropna()` - return a new Data Frame with no empty cells

In [35]:
df = pd.read_csv('./data.csv')
new_df = df.dropna()
print(new_df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.5
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.5
37         60    100       120     300.1
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.1
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

If you want to change the original DataFrame, use the `inplace = True` argument:

In [ ]:
df.dropna(inplace = True)
print(df.to_string())

It will NOT return a new DataFrame, but it will remove all rows containing NULL values from the original DataFrame.

if you want to remove row, based on any specified column, specify it with subset attribute. Like if Date column have null value you want remove the row, then use it

In [39]:
df.dropna(subset=['Duration'], inplace = True)

if any other column have null value, those will not be removed.

## Replace Empty Values

`fillna()` method allows to replace empty cells with a value.

In [40]:
df.fillna(130, inplace = True)

It will replace all empty cells in the whole data frame. If you want to replace empty value on specified column, then specify them.

In [ ]:
df["Calories"].fillna(130, inplace = True)

**For multiple column:**

In [42]:
fill_values = {
    "Calories": 130,
    "Protein": 0.0,
    "Fat": 0.0
}
df.fillna(value=fill_values, inplace=True)

### Replacing with Mean, Median, Mode

In [ ]:
x = df["Calories"].mean() # you can also use median(), mode()[0]
df["Calories"].fillna(x, inplace = True)

### Forward & Backward Filling

Forward filling fills missing values with the last known value that appeared before the NaN. This is useful when you assume that the previous value is the best estimate for the missing value. Backward filling fills missing values with the next known value that appears after the NaN. This is useful when you assume that the next value is the best estimate for the missing value.. It is useful in time series data or other sequential data.

In [ ]:
df_ffilled = df.fillna(method='ffill')
df_bfilled = df.fillna(method='bfill')

## Remove Duplicates

- `duplicated()` method returns a Boolean values for each row

In [44]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
164    False
165    False
166    False
167    False
168    False
Length: 164, dtype: bool

- `drop_duplicates()` is used to remove duplicate value

In [45]:
  df.drop_duplicates(inplace = True)

## Wrong Format

Cells with data of wrong format can make it difficult, or even impossible, to analyze data.

- `to_datetime()` is used to format the date

In [ ]:
  df['Date'] = pd.to_datetime(df['Date'])

## Wrong Data

Wrong data does not have to be empty cells or wrong format, it can just be wrong, like if someone registered "199" instead of 1.99.

For small data sets you might be able to replace the wrong data one by one, but not for big data set

In [47]:
df.loc[7, 'Duration'] = 45

To replace wrong data for larger data sets you can create some rules, e.g. set some boundaries for legal values, and replace any values that are outside of the boundaries.

In [ ]:
for x in df.index:
  if df.loc[x, "Duration"] > 120:
    df.loc[x, "Duration"] = 120

# Column Operation

- `df.columnName` or `df["column name"]` return specified column
- `df[["first","second"]]` select multiple column
- `df['column_name'].apply(func)` - applies a function to each value in the column.

you can apply all the inspection method to column

## Column Insertion

1. **Assigning a New Column Directly:** You can directly assign a new column by specifying the column name and the values. If the column name already exists, this will overwrite the existing column.

In [48]:
   df = pd.DataFrame({
       "A": [1, 2, 3],
       "B": [4, 5, 6]
   })
   df["C"] = [7, 8, 9]

2. **insert() method:** allow to insert a column at a specific location

In [50]:
   df.insert(1, "D", [10, 11, 12])

3. **assign() method:** return new dataframe with additional column. it does not modify the original dataframe uunless you reassign it.

In [51]:
   df = df.assign(E=[13, 14, 15])

In [52]:
df

   A   D  B  C   E
0  1  10  4  7  13
1  2  11  5  8  14
2  3  12  6  9  15

4. **Index Based Assignment:** you can use `loc()` or `iloc()` method.

In [53]:
   df.loc[:, "F"] = [16, 17, 18]

## Column Updation

1. **Direct Assignment:**

In [54]:
   df = pd.DataFrame({
       "A": [1, 2, 3],
       "B": [4, 5, 6]
   })
   df["A"] = [10, 20, 30]

- `df["A"] = 10` - update all value of a column
- `df.loc[df['A'] == 2, 'B'] = 10` - update specific field of a column

2. **replace():**

In [56]:
   df["A"] = df["A"].replace({10: 100, 99: 999})

3. **update():**

In [ ]:
   update_series = pd.Series([200, 300], index=[0, 2])
   df["A"].update(update_series)

## Column Deletion

1. **drop():**

In [58]:
   df.drop(columns=['B'], inplace=True)

2. **del:**

In [ ]:
   del df['B']

3. **pop():**

In [ ]:
   droppedCol = df.pop('B')

4. **dropna():** `axis=1` parameter in `dropna()` method is use to remove column which have empty value, `axis=0` is use to remove row which have empty value. Default value of axis parameter is 0

# Feature Scaling

Feature Scaling is a technique to standardize the independent features present in the data in a fixed range.

## Standardization (Z-score normalization)

Standardization scales the features such that they have a mean of 0 and a standard deviation of 1. This method is useful when the features have different units or vastly different ranges. It is used when the data follows a normal distribution.

In [63]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_standardized = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

## Min-Max Scaling (Normalization)

Min-Max scaling scales the features to a fixed range, usually 0 to 1. This method is useful when the data is not normally distributed or the model requires the data in a specific range like neural networks

In [64]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_normalized = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

## Robust Scaling

Robust scaling uses the median and the interquartile range (IQR) for scaling, making it robust to outliers. This method is useful when the data contains many outliers.

In [65]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
df_robust_scaled = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

## MaxAbs Scaling

MaxAbs scaling scales each feature by its maximum absolute value, preserving the sparsity of the data. This method is useful for data that is sparse (contains many zeros).

In [66]:
from sklearn.preprocessing import MaxAbsScaler
scaler = MaxAbsScaler()
df_maxabs_scaled = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)

# Filtering

1. **Boolean Indexing:**

In [67]:
filtered_df = df[df['A'] > 2] # Filter rows where column __A__ is greater than 2

2. **query():**

In [68]:
filtered_df = df.query('A > 2')

3. **Combining Multiple Conditions:**

In [ ]:
filtered_df = df[(df['A'] > 2) & (df['C'] == 'foo')]

4. **loc[]:**

In [70]:
df.loc[df['A'] > 2]

     A
0  200
1   20
2  300

5. **isin():** filter rows based on multiple specific values in a column.

In [71]:
filtered_df = df[df['A'].isin([2,4])] # retur data, df['A'].isin([2,4]) return boolean

# Concatenating

**Rows:**

In [ ]:
concat_rows = pd.concat([df1, df2])

**Columns:**

In [ ]:
concat_cols = pd.concat([df1, df3], axis=1)

# Merging

## Inner Join

only includes rows with matching keys in both DataFrames

In [ ]:
merged_inner = pd.merge(df1, df2, on='id')

## Outer Join

includes all rows when there is a match in one of the DataFrames

In [ ]:
merged_outer = pd.merge(df1, df2, on='id', how='outer')

if you have common column name, specify it with `on` attribute, if not, then use `left_on` and `right_on` attribute

`joined = df1.join(df2, how='inner')` is used to join dataframes on their index

## Left Join

includes all rows from the left DataFrame and matched rows from the right DataFrame

In [ ]:
merged_left = pd.merge(df1, df2, on='id', how='left')

## Right Join

includes all rows from the right DataFrame and matched rows from the left DataFrame

In [ ]:
merged_right = pd.merge(df1, df2, on='id', how='right')

# Transformation

1. **apply():**
   It allows to apply a function along the axis (rows or columns).

In [73]:
df_sum = df.apply(lambda row: row.sum(), axis=1) # apply on row
df_sum = df.apply(lambda col: col.sum(), axis=0) # apply on column

2. **applymap():**
   It allows to apply a function to each element.

In [ ]:
df_incremented = df.applymap(lambda x: x + 1)

3. **map():**
   It allows to apply a function to each element of a Series.

In [75]:
df['A'] = df['A'].map(lambda x: x * 2)

4. **transform():**